// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: apps/web/scripts/generate-storybook-design-exports.mjs
// Source: designs/components/form-field/text-field/text-field.json

export default {
  id: "components-form-field-text-field-design-export",
  title: "Reference/Components/Form Field/Text Field",
  tags: ['!autodocs'],
  parameters: {
    layout: "padded",
    docs: { disable: true },
  },
};

export const DesignExport = {
  name: 'Design export',
  render: () => `
    <style>
      .de-wrap { padding: 1rem; }
      .de-desc { margin: 0 0 1rem; color: var(--color-fg-secondary); font-size: 0.875rem; }
      .de-variant { margin: 1rem 0 0.5rem; font-size: 0.95rem; }
      .de-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem; align-items: start; }
      .de-item { margin: 0; padding: 0.75rem; border-radius: 0.5rem; border: 1px solid var(--color-separator); background: var(--color-bg); }
      .de-img { width: 100%; height: auto; display: block; }
      .de-cap { margin-top: 0.5rem; font-size: 0.875rem; color: var(--color-fg-secondary); }
    </style>
    <div class="de-wrap">
      <p class="de-desc">Text input field for entering short textual values.</p>
<h4 class="de-variant">default-default</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/form-field/text-field/variants/default-default/focus.svg" alt="default-default / focus" loading="lazy" />
  <figcaption class="de-cap">default-default / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/form-field/text-field/variants/default-default/default.svg" alt="default-default / default" loading="lazy" />
  <figcaption class="de-cap">default-default / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/form-field/text-field/variants/default-default/hover.svg" alt="default-default / hover" loading="lazy" />
  <figcaption class="de-cap">default-default / hover</figcaption>
</figure>
</div>
<h4 class="de-variant">readonly-multiple-text-rows</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/form-field/text-field/variants/readonly-multiple-text-rows/default.svg" alt="readonly-multiple-text-rows / default" loading="lazy" />
  <figcaption class="de-cap">readonly-multiple-text-rows / default</figcaption>
</figure>
</div>
<h4 class="de-variant">readonly-informative</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/form-field/text-field/variants/readonly-informative/default.svg" alt="readonly-informative / default" loading="lazy" />
  <figcaption class="de-cap">readonly-informative / default</figcaption>
</figure>
</div>
<h4 class="de-variant">default-error</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/form-field/text-field/variants/default-error/default.svg" alt="default-error / default" loading="lazy" />
  <figcaption class="de-cap">default-error / default</figcaption>
</figure>
</div>
<h4 class="de-variant">default-informative</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/form-field/text-field/variants/default-informative/default.svg" alt="default-informative / default" loading="lazy" />
  <figcaption class="de-cap">default-informative / default</figcaption>
</figure>
</div>
<h4 class="de-variant">readonly-default</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/form-field/text-field/variants/readonly-default/default.svg" alt="readonly-default / default" loading="lazy" />
  <figcaption class="de-cap">readonly-default / default</figcaption>
</figure>
</div>
    </div>
  `,
};
