// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: apps/web/scripts/generate-storybook-design-exports.mjs
// Source: designs/components/button/standard-button/standard-button.json

export default {
  id: "components-button-standard-button-design-export",
  title: "Reference/Components/Button/Standard Button",
  tags: ['!autodocs'],
  parameters: {
    layout: "padded",
    docs: { disable: true },
  },
};

export const DesignExport = {
  name: 'Design export',
  render: () => `
    <style>
      .de-wrap { padding: 1rem; }
      .de-desc { margin: 0 0 1rem; color: var(--color-fg-secondary); font-size: 0.875rem; }
      .de-variant { margin: 1rem 0 0.5rem; font-size: 0.95rem; }
      .de-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem; align-items: start; }
      .de-item { margin: 0; padding: 0.75rem; border-radius: 0.5rem; border: 1px solid var(--color-separator); background: var(--color-bg); }
      .de-img { width: 100%; height: auto; display: block; }
      .de-cap { margin-top: 0.5rem; font-size: 0.875rem; color: var(--color-fg-secondary); }
    </style>
    <div class="de-wrap">
      <p class="de-desc">standard-button component (auto-generated metadata).</p>
<h4 class="de-variant">small-secondary</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-secondary/focus.svg" alt="small-secondary / focus" loading="lazy" />
  <figcaption class="de-cap">small-secondary / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-secondary/default.svg" alt="small-secondary / default" loading="lazy" />
  <figcaption class="de-cap">small-secondary / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-secondary/hover.svg" alt="small-secondary / hover" loading="lazy" />
  <figcaption class="de-cap">small-secondary / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-secondary/pressed.svg" alt="small-secondary / pressed" loading="lazy" />
  <figcaption class="de-cap">small-secondary / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">large-filled-tonal</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-filled-tonal/focus.svg" alt="large-filled-tonal / focus" loading="lazy" />
  <figcaption class="de-cap">large-filled-tonal / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-filled-tonal/default.svg" alt="large-filled-tonal / default" loading="lazy" />
  <figcaption class="de-cap">large-filled-tonal / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-filled-tonal/hover.svg" alt="large-filled-tonal / hover" loading="lazy" />
  <figcaption class="de-cap">large-filled-tonal / hover</figcaption>
</figure>
</div>
<h4 class="de-variant">regular-filledtonal</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-filledtonal/default.svg" alt="regular-filledtonal / default" loading="lazy" />
  <figcaption class="de-cap">regular-filledtonal / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-filledtonal/hover.svg" alt="regular-filledtonal / hover" loading="lazy" />
  <figcaption class="de-cap">regular-filledtonal / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-filledtonal/pressed.svg" alt="regular-filledtonal / pressed" loading="lazy" />
  <figcaption class="de-cap">regular-filledtonal / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">regular-secondary</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-secondary/focus.svg" alt="regular-secondary / focus" loading="lazy" />
  <figcaption class="de-cap">regular-secondary / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-secondary/default.svg" alt="regular-secondary / default" loading="lazy" />
  <figcaption class="de-cap">regular-secondary / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-secondary/hover.svg" alt="regular-secondary / hover" loading="lazy" />
  <figcaption class="de-cap">regular-secondary / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-secondary/pressed.svg" alt="regular-secondary / pressed" loading="lazy" />
  <figcaption class="de-cap">regular-secondary / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">small-filled-tonal</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-filled-tonal/focus.svg" alt="small-filled-tonal / focus" loading="lazy" />
  <figcaption class="de-cap">small-filled-tonal / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-filled-tonal/default.svg" alt="small-filled-tonal / default" loading="lazy" />
  <figcaption class="de-cap">small-filled-tonal / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-filled-tonal/hover.svg" alt="small-filled-tonal / hover" loading="lazy" />
  <figcaption class="de-cap">small-filled-tonal / hover</figcaption>
</figure>
</div>
<h4 class="de-variant">small-primary</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-primary/focus.svg" alt="small-primary / focus" loading="lazy" />
  <figcaption class="de-cap">small-primary / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-primary/default.svg" alt="small-primary / default" loading="lazy" />
  <figcaption class="de-cap">small-primary / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-primary/hover.svg" alt="small-primary / hover" loading="lazy" />
  <figcaption class="de-cap">small-primary / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-primary/pressed.svg" alt="small-primary / pressed" loading="lazy" />
  <figcaption class="de-cap">small-primary / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">large-txt-only</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-txt-only/focus.svg" alt="large-txt-only / focus" loading="lazy" />
  <figcaption class="de-cap">large-txt-only / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-txt-only/default.svg" alt="large-txt-only / default" loading="lazy" />
  <figcaption class="de-cap">large-txt-only / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-txt-only/hover.svg" alt="large-txt-only / hover" loading="lazy" />
  <figcaption class="de-cap">large-txt-only / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-txt-only/pressed.svg" alt="large-txt-only / pressed" loading="lazy" />
  <figcaption class="de-cap">large-txt-only / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">large-secondary</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-secondary/focus.svg" alt="large-secondary / focus" loading="lazy" />
  <figcaption class="de-cap">large-secondary / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-secondary/default.svg" alt="large-secondary / default" loading="lazy" />
  <figcaption class="de-cap">large-secondary / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-secondary/hover.svg" alt="large-secondary / hover" loading="lazy" />
  <figcaption class="de-cap">large-secondary / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-secondary/pressed.svg" alt="large-secondary / pressed" loading="lazy" />
  <figcaption class="de-cap">large-secondary / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">regular-filled-tonal</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-filled-tonal/focus.svg" alt="regular-filled-tonal / focus" loading="lazy" />
  <figcaption class="de-cap">regular-filled-tonal / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-filled-tonal/default.svg" alt="regular-filled-tonal / default" loading="lazy" />
  <figcaption class="de-cap">regular-filled-tonal / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-filled-tonal/hover.svg" alt="regular-filled-tonal / hover" loading="lazy" />
  <figcaption class="de-cap">regular-filled-tonal / hover</figcaption>
</figure>
</div>
<h4 class="de-variant">regular-txt-only</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-txt-only/focus.svg" alt="regular-txt-only / focus" loading="lazy" />
  <figcaption class="de-cap">regular-txt-only / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-txt-only/default.svg" alt="regular-txt-only / default" loading="lazy" />
  <figcaption class="de-cap">regular-txt-only / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-txt-only/hover.svg" alt="regular-txt-only / hover" loading="lazy" />
  <figcaption class="de-cap">regular-txt-only / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-txt-only/pressed.svg" alt="regular-txt-only / pressed" loading="lazy" />
  <figcaption class="de-cap">regular-txt-only / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">large-primary</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-primary/focus.svg" alt="large-primary / focus" loading="lazy" />
  <figcaption class="de-cap">large-primary / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-primary/default.svg" alt="large-primary / default" loading="lazy" />
  <figcaption class="de-cap">large-primary / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-primary/hover.svg" alt="large-primary / hover" loading="lazy" />
  <figcaption class="de-cap">large-primary / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-primary/pressed.svg" alt="large-primary / pressed" loading="lazy" />
  <figcaption class="de-cap">large-primary / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">small-txt-only</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-txt-only/focus.svg" alt="small-txt-only / focus" loading="lazy" />
  <figcaption class="de-cap">small-txt-only / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-txt-only/default.svg" alt="small-txt-only / default" loading="lazy" />
  <figcaption class="de-cap">small-txt-only / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-txt-only/hover.svg" alt="small-txt-only / hover" loading="lazy" />
  <figcaption class="de-cap">small-txt-only / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-txt-only/pressed.svg" alt="small-txt-only / pressed" loading="lazy" />
  <figcaption class="de-cap">small-txt-only / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">small-filledtonal</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-filledtonal/default.svg" alt="small-filledtonal / default" loading="lazy" />
  <figcaption class="de-cap">small-filledtonal / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-filledtonal/hover.svg" alt="small-filledtonal / hover" loading="lazy" />
  <figcaption class="de-cap">small-filledtonal / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/small-filledtonal/pressed.svg" alt="small-filledtonal / pressed" loading="lazy" />
  <figcaption class="de-cap">small-filledtonal / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">regular-primary</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-primary/focus.svg" alt="regular-primary / focus" loading="lazy" />
  <figcaption class="de-cap">regular-primary / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-primary/default.svg" alt="regular-primary / default" loading="lazy" />
  <figcaption class="de-cap">regular-primary / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-primary/hover.svg" alt="regular-primary / hover" loading="lazy" />
  <figcaption class="de-cap">regular-primary / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/regular-primary/pressed.svg" alt="regular-primary / pressed" loading="lazy" />
  <figcaption class="de-cap">regular-primary / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">large-filledtonal</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-filledtonal/default.svg" alt="large-filledtonal / default" loading="lazy" />
  <figcaption class="de-cap">large-filledtonal / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-filledtonal/hover.svg" alt="large-filledtonal / hover" loading="lazy" />
  <figcaption class="de-cap">large-filledtonal / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/button/standard-button/variants/large-filledtonal/pressed.svg" alt="large-filledtonal / pressed" loading="lazy" />
  <figcaption class="de-cap">large-filledtonal / pressed</figcaption>
</figure>
</div>
    </div>
  `,
};
