// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: apps/web/scripts/generate-storybook-design-exports.mjs
// Source: designs/components/card/section-card/section-card.json

export default {
  id: "components-card-section-card-design-export",
  title: "Components/Card/Section Card",
  tags: ['!autodocs'],
  parameters: {
    layout: "padded",
    docs: { disable: true },
  },
};

export const DesignExport = {
  name: 'Design export',
  render: () => `
    <style>
      .de-wrap { padding: 1rem; }
      .de-desc { margin: 0 0 1rem; color: var(--color-fg-secondary); font-size: 0.875rem; }
      .de-variant { margin: 1rem 0 0.5rem; font-size: 0.95rem; }
      .de-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem; align-items: start; }
      .de-item { margin: 0; padding: 0.75rem; border-radius: 0.5rem; border: 1px solid var(--color-separator); background: var(--color-bg); }
      .de-img { width: 100%; height: auto; display: block; }
      .de-cap { margin-top: 0.5rem; font-size: 0.875rem; color: var(--color-fg-secondary); }
    </style>
    <div class="de-wrap">
      <p class="de-desc">Section header plus bordered body card (`.section-card` in the web app).</p>
<h4 class="de-variant">offers</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/card/section-card/variants/offers/default.svg" alt="offers / default" loading="lazy" />
  <figcaption class="de-cap">offers / default</figcaption>
</figure>
</div>
<h4 class="de-variant">bookings</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/card/section-card/variants/bookings/default.svg" alt="bookings / default" loading="lazy" />
  <figcaption class="de-cap">bookings / default</figcaption>
</figure>
</div>
<h4 class="de-variant">accounts-investment</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/card/section-card/variants/accounts-investment/default.svg" alt="accounts-investment / default" loading="lazy" />
  <figcaption class="de-cap">accounts-investment / default</figcaption>
</figure>
</div>
<h4 class="de-variant">recipients</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/card/section-card/variants/recipients/default.svg" alt="recipients / default" loading="lazy" />
  <figcaption class="de-cap">recipients / default</figcaption>
</figure>
</div>
<h4 class="de-variant">recurring-payments</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/card/section-card/variants/recurring-payments/default.svg" alt="recurring-payments / default" loading="lazy" />
  <figcaption class="de-cap">recurring-payments / default</figcaption>
</figure>
</div>
<h4 class="de-variant">pending-payments</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/card/section-card/variants/pending-payments/default.svg" alt="pending-payments / default" loading="lazy" />
  <figcaption class="de-cap">pending-payments / default</figcaption>
</figure>
</div>
<h4 class="de-variant">other-products</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/card/section-card/variants/other-products/default.svg" alt="other-products / default" loading="lazy" />
  <figcaption class="de-cap">other-products / default</figcaption>
</figure>
</div>
    </div>
  `,
};
