// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: apps/web/scripts/generate-storybook-design-exports.mjs
// Source: designs/components/menu/menu-sidebar/menu-sidebar.json

export default {
  id: "components-menu-menu-sidebar-design-export",
  title: "Components/Menu/Menu Sidebar",
  tags: ['!autodocs'],
  parameters: {
    layout: "padded",
    docs: { disable: true },
  },
};

export const DesignExport = {
  name: 'Design export',
  render: () => `
    <style>
      .de-wrap { padding: 1rem; }
      .de-desc { margin: 0 0 1rem; color: var(--color-fg-secondary); font-size: 0.875rem; }
      .de-variant { margin: 1rem 0 0.5rem; font-size: 0.95rem; }
      .de-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem; align-items: start; }
      .de-item { margin: 0; padding: 0.75rem; border-radius: 0.5rem; border: 1px solid var(--color-separator); background: var(--color-bg); }
      .de-img { width: 100%; height: auto; display: block; }
      .de-cap { margin-top: 0.5rem; font-size: 0.875rem; color: var(--color-fg-secondary); }
    </style>
    <div class="de-wrap">
      <p class="de-desc">Sidebar navigation menu items.</p>
<h4 class="de-variant">sidebar-nav-selected</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/menu/menu-sidebar/variants/sidebar-nav-selected/default.svg" alt="sidebar-nav-selected / default" loading="lazy" />
  <figcaption class="de-cap">sidebar-nav-selected / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/menu/menu-sidebar/variants/sidebar-nav-selected/hover.svg" alt="sidebar-nav-selected / hover" loading="lazy" />
  <figcaption class="de-cap">sidebar-nav-selected / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/menu/menu-sidebar/variants/sidebar-nav-selected/focus.svg" alt="sidebar-nav-selected / focus" loading="lazy" />
  <figcaption class="de-cap">sidebar-nav-selected / focus</figcaption>
</figure>
</div>
<h4 class="de-variant">sidebar-nav-unselected</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/menu/menu-sidebar/variants/sidebar-nav-unselected/default.svg" alt="sidebar-nav-unselected / default" loading="lazy" />
  <figcaption class="de-cap">sidebar-nav-unselected / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/menu/menu-sidebar/variants/sidebar-nav-unselected/hover.svg" alt="sidebar-nav-unselected / hover" loading="lazy" />
  <figcaption class="de-cap">sidebar-nav-unselected / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/menu/menu-sidebar/variants/sidebar-nav-unselected/focus.svg" alt="sidebar-nav-unselected / focus" loading="lazy" />
  <figcaption class="de-cap">sidebar-nav-unselected / focus</figcaption>
</figure>
</div>
    </div>
  `,
};
