// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: apps/web/scripts/generate-storybook-design-exports.mjs
// Source: designs/components/selection-control/toggle-switch/toggle-switch.json

export default {
  id: "components-selection-control-toggle-switch-design-export",
  title: "Components/Selection Control/Toggle Switch",
  tags: ['!autodocs'],
  parameters: {
    layout: "padded",
    docs: { disable: true },
  },
};

export const DesignExport = {
  name: 'Design export',
  render: () => `
    <style>
      .de-wrap { padding: 1rem; }
      .de-desc { margin: 0 0 1rem; color: var(--color-fg-secondary); font-size: 0.875rem; }
      .de-variant { margin: 1rem 0 0.5rem; font-size: 0.95rem; }
      .de-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem; align-items: start; }
      .de-item { margin: 0; padding: 0.75rem; border-radius: 0.5rem; border: 1px solid var(--color-separator); background: var(--color-bg); }
      .de-img { width: 100%; height: auto; display: block; }
      .de-cap { margin-top: 0.5rem; font-size: 0.875rem; color: var(--color-fg-secondary); }
    </style>
    <div class="de-wrap">
      <p class="de-desc">Selection control for enabling or disabling a setting.</p>
<h4 class="de-variant">regular-active</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/selection-control/toggle-switch/variants/regular-active/default.svg" alt="regular-active / default" loading="lazy" />
  <figcaption class="de-cap">regular-active / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/selection-control/toggle-switch/variants/regular-active/hover.svg" alt="regular-active / hover" loading="lazy" />
  <figcaption class="de-cap">regular-active / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/selection-control/toggle-switch/variants/regular-active/focus.svg" alt="regular-active / focus" loading="lazy" />
  <figcaption class="de-cap">regular-active / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/selection-control/toggle-switch/variants/regular-active/pressed.svg" alt="regular-active / pressed" loading="lazy" />
  <figcaption class="de-cap">regular-active / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">regular-inactive</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/selection-control/toggle-switch/variants/regular-inactive/default.svg" alt="regular-inactive / default" loading="lazy" />
  <figcaption class="de-cap">regular-inactive / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/selection-control/toggle-switch/variants/regular-inactive/hover.svg" alt="regular-inactive / hover" loading="lazy" />
  <figcaption class="de-cap">regular-inactive / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/selection-control/toggle-switch/variants/regular-inactive/focus.svg" alt="regular-inactive / focus" loading="lazy" />
  <figcaption class="de-cap">regular-inactive / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/selection-control/toggle-switch/variants/regular-inactive/pressed.svg" alt="regular-inactive / pressed" loading="lazy" />
  <figcaption class="de-cap">regular-inactive / pressed</figcaption>
</figure>
</div>
    </div>
  `,
};
