// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: apps/web/scripts/generate-storybook-design-exports.mjs
// Source: designs/screens/details-of-position/details-of-position.json

export default {
  id: "pages-details-of-position-design-export",
  title: "Reference/Pages/Details Of Position",
  tags: ['!autodocs'],
  parameters: {
    layout: "fullscreen",
    docs: { disable: true },
  },
};

export const DesignExport = {
  name: 'Design export',
  render: () => `
    <style>
      .de-wrap { padding: 1rem; }
      .de-desc { margin: 0 0 1rem; color: var(--color-fg-secondary); font-size: 0.875rem; }
      .de-variant { margin: 1rem 0 0.5rem; font-size: 0.95rem; }
      .de-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem; align-items: start; }
      .de-item { margin: 0; padding: 0.75rem; border-radius: 0.5rem; border: 1px solid var(--color-separator); background: var(--color-bg); }
      .de-img { width: 100%; height: auto; display: block; }
      .de-cap { margin-top: 0.5rem; font-size: 0.875rem; color: var(--color-fg-secondary); }
      .de-grid--screen { grid-template-columns: repeat(auto-fit, minmax(min(100%, 390px), 1fr)); }
      .de-img--screen { max-height: 85vh; object-fit: contain; object-position: top center; }
    </style>
    <div class="de-wrap">
      <p class="de-desc">Position detail shell screen with persona-driven layout variants (key figures + holdings list).</p>
<h4 class="de-variant">a</h4>
<div class="de-grid de-grid--screen">
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/details-of-position/variants/a/desktop-default/default.svg" alt="a / desktop-default" loading="lazy" />
  <figcaption class="de-cap">a / desktop-default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/details-of-position/variants/a/mobile-default/default.svg" alt="a / mobile-default" loading="lazy" />
  <figcaption class="de-cap">a / mobile-default</figcaption>
</figure>
</div>
<h4 class="de-variant">b</h4>
<div class="de-grid de-grid--screen">
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/details-of-position/variants/b/mobile-default/default.svg" alt="b / mobile-default" loading="lazy" />
  <figcaption class="de-cap">b / mobile-default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/details-of-position/variants/b/desktop-default/default.svg" alt="b / desktop-default" loading="lazy" />
  <figcaption class="de-cap">b / desktop-default</figcaption>
</figure>
</div>
    </div>
  `,
};
