// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: apps/web/scripts/generate-storybook-design-exports.mjs
// Source: designs/components/selection-control/paginator/paginator.json

export default {
  id: "components-selection-control-paginator-design-export",
  title: "Reference/Components/Selection Control/Paginator",
  tags: ['!autodocs'],
  parameters: {
    layout: "padded",
    docs: { disable: true },
  },
};

export const DesignExport = {
  name: 'Design export',
  render: () => `
    <style>
      .de-wrap { padding: 1rem; }
      .de-desc { margin: 0 0 1rem; color: var(--color-fg-secondary); font-size: 0.875rem; }
      .de-variant { margin: 1rem 0 0.5rem; font-size: 0.95rem; }
      .de-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem; align-items: start; }
      .de-item { margin: 0; padding: 0.75rem; border-radius: 0.5rem; border: 1px solid var(--color-separator); background: var(--color-bg); }
      .de-img { width: 100%; height: auto; display: block; }
      .de-cap { margin-top: 0.5rem; font-size: 0.875rem; color: var(--color-fg-secondary); }
    </style>
    <div class="de-wrap">
      <p class="de-desc">Compact pagination indicator for short sequences (e.g. carousels/onboarding).</p>
<h4 class="de-variant">3-dots-left-active</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/selection-control/paginator/variants/3-dots-left-active/default.svg" alt="3-dots-left-active / default" loading="lazy" />
  <figcaption class="de-cap">3-dots-left-active / default</figcaption>
</figure>
</div>
<h4 class="de-variant">3-dots-mid-active</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/selection-control/paginator/variants/3-dots-mid-active/default.svg" alt="3-dots-mid-active / default" loading="lazy" />
  <figcaption class="de-cap">3-dots-mid-active / default</figcaption>
</figure>
</div>
<h4 class="de-variant">3-dots-right-active</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/selection-control/paginator/variants/3-dots-right-active/default.svg" alt="3-dots-right-active / default" loading="lazy" />
  <figcaption class="de-cap">3-dots-right-active / default</figcaption>
</figure>
</div>
    </div>
  `,
};
