// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: apps/web/scripts/generate-storybook-design-exports.mjs
// Source: designs/components/list-item/selection-list-item/selection-list-item.json

export default {
  id: "components-list-item-selection-list-item-design-export",
  title: "Components/List Item/Selection List Item",
  tags: ['!autodocs'],
  parameters: {
    layout: "padded",
    docs: { disable: true },
  },
};

export const DesignExport = {
  name: 'Design export',
  render: () => `
    <style>
      .de-wrap { padding: 1rem; }
      .de-desc { margin: 0 0 1rem; color: var(--color-fg-secondary); font-size: 0.875rem; }
      .de-variant { margin: 1rem 0 0.5rem; font-size: 0.95rem; }
      .de-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem; align-items: start; }
      .de-item { margin: 0; padding: 0.75rem; border-radius: 0.5rem; border: 1px solid var(--color-separator); background: var(--color-bg); }
      .de-img { width: 100%; height: auto; display: block; }
      .de-cap { margin-top: 0.5rem; font-size: 0.875rem; color: var(--color-fg-secondary); }
    </style>
    <div class="de-wrap">
      <p class="de-desc">Selection list item variants (e.g. countries).</p>
<h4 class="de-variant">grouped-bottom-country</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/list-item/selection-list-item/variants/grouped-bottom-country/default.svg" alt="grouped-bottom-country / default" loading="lazy" />
  <figcaption class="de-cap">grouped-bottom-country / default</figcaption>
</figure>
</div>
<h4 class="de-variant">grouped-mid-country</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/list-item/selection-list-item/variants/grouped-mid-country/default.svg" alt="grouped-mid-country / default" loading="lazy" />
  <figcaption class="de-cap">grouped-mid-country / default</figcaption>
</figure>
</div>
<h4 class="de-variant">grouped-top-country</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/list-item/selection-list-item/variants/grouped-top-country/default.svg" alt="grouped-top-country / default" loading="lazy" />
  <figcaption class="de-cap">grouped-top-country / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/list-item/selection-list-item/variants/grouped-top-country/hover.svg" alt="grouped-top-country / hover" loading="lazy" />
  <figcaption class="de-cap">grouped-top-country / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/list-item/selection-list-item/variants/grouped-top-country/focus.svg" alt="grouped-top-country / focus" loading="lazy" />
  <figcaption class="de-cap">grouped-top-country / focus</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/list-item/selection-list-item/variants/grouped-top-country/pressed.svg" alt="grouped-top-country / pressed" loading="lazy" />
  <figcaption class="de-cap">grouped-top-country / pressed</figcaption>
</figure>
</div>
    </div>
  `,
};
