import { fillProbeValues, readRootCssVar } from './utils/css-var-probe.js';

export default {
  title: 'Live/Foundations/Typography',
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component:
          'Bundled text styles from `css/typography.css` (generated by `npm run tokens:build`). ' +
          'Two-line rows use `.type-stack-tight` + `.type-sm`/`.type-xs` + `.type-trim`. ' +
          'Chrome applies `text-box-trim` when supported; modals and carousels opt out to margin trim.',
      },
    },
  },
};

const stackDemo = `
  <div style="max-width:20rem;padding:var(--space-3);border:1px dashed var(--color-separator);border-radius:var(--radius-regular);">
    <p style="margin:0 0 var(--space-2);font-size:var(--fs-text-xs);color:var(--color-fg-secondary);">
      Title + subtitle stack (product item / list row pattern)
    </p>
    <div class="type-stack-tight" style="background:color-mix(in srgb, var(--color-fg) 6%, transparent);">
      <span class="type-sm type-trim" style="color:var(--color-fg);">Household</span>
      <span class="type-xs type-trim" style="color:var(--color-fg-secondary);">CH35 0900 0000 2470 2920 1</span>
    </div>
  </div>
`;

export const TrimStack = {
  name: 'Leading trim — title + subtitle',
  render: () => stackDemo,
};

export const StyleScale = {
  name: 'Type scale (untrimmed reference)',
  render: () => `
    <div style="display:flex;flex-direction:column;gap:var(--space-3);max-width:32rem;">
      <p class="type-hero">Hero</p>
      <p class="type-h1">Heading 1</p>
      <p class="type-h2">Heading 2</p>
      <p class="type-lg">Text large</p>
      <p class="type-md">Text main (16px base)</p>
      <p class="type-sm">Text small</p>
      <p class="type-xs">Text extra-small</p>
      <p class="type-caption">Caption</p>
    </div>
  `,
};

const trimProbeDl = `
  <dl data-probe="trim-tokens" style="margin:0;font-size:var(--fs-text-sm);line-height:var(--lh-text);display:grid;grid-template-columns:auto 1fr;gap:var(--space-2) var(--space-4);max-width:28rem;">
    <dt style="color:var(--color-fg-secondary);">--text-row-gap</dt><dd data-probe-dd="text-row-gap" style="margin:0;font-family:monospace;">…</dd>
    <dt style="color:var(--color-fg-secondary);">--list-row-pad-y</dt><dd data-probe-dd="list-row-pad-y" style="margin:0;font-family:monospace;">…</dd>
    <dt style="color:var(--color-fg-secondary);">--list-row-pad-x</dt><dd data-probe-dd="list-row-pad-x" style="margin:0;font-family:monospace;">…</dd>
    <dt style="color:var(--color-fg-secondary);">--list-row-gap</dt><dd data-probe-dd="list-row-gap" style="margin:0;font-family:monospace;">…</dd>
    <dt style="color:var(--color-fg-secondary);">--trim-top-text-sm</dt><dd data-probe-dd="trim-top-text-sm" style="margin:0;font-family:monospace;">…</dd>
    <dt style="color:var(--color-fg-secondary);">--trim-bottom-text-sm</dt><dd data-probe-dd="trim-bottom-text-sm" style="margin:0;font-family:monospace;">…</dd>
    <dt style="color:var(--color-fg-secondary);">--trim-top-text-xs</dt><dd data-probe-dd="trim-top-text-xs" style="margin:0;font-family:monospace;">…</dd>
    <dt style="color:var(--color-fg-secondary);">--trim-bottom-text-xs</dt><dd data-probe-dd="trim-bottom-text-xs" style="margin:0;font-family:monospace;">…</dd>
  </dl>
`;

export const TrimTokens = {
  name: 'Trim tokens (computed)',
  render: () => `
    ${trimProbeDl}
    <p style="margin:var(--space-3) 0 0;font-size:var(--fs-text-xs);color:var(--color-fg-secondary);max-width:28rem;">
      Values are read from <code>getComputedStyle(document.documentElement)</code> after load.
      List row padding comes from <code>alias.component.list-row</code> (Figma account row: space/3 = 16dp).
    </p>
  `,
  play: async ({ canvasElement }) => {
    fillProbeValues(canvasElement, {
      'text-row-gap': readRootCssVar('--text-row-gap'),
      'list-row-pad-y': readRootCssVar('--list-row-pad-y'),
      'list-row-pad-x': readRootCssVar('--list-row-pad-x'),
      'list-row-gap': readRootCssVar('--list-row-gap'),
      'trim-top-text-sm': readRootCssVar('--trim-top-text-sm'),
      'trim-bottom-text-sm': readRootCssVar('--trim-bottom-text-sm'),
      'trim-top-text-xs': readRootCssVar('--trim-top-text-xs'),
      'trim-bottom-text-xs': readRootCssVar('--trim-bottom-text-xs'),
    });
  },
};
