// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: apps/web/scripts/generate-storybook-design-exports.mjs
// Source: designs/components/expander/expander.json

export default {
  id: "components-expander-design-export",
  title: "Components/Expander",
  tags: ['!autodocs'],
  parameters: {
    layout: "padded",
    docs: { disable: true },
  },
};

export const DesignExport = {
  name: 'Design export',
  render: () => `
    <style>
      .de-wrap { padding: 1rem; }
      .de-desc { margin: 0 0 1rem; color: var(--color-fg-secondary); font-size: 0.875rem; }
      .de-variant { margin: 1rem 0 0.5rem; font-size: 0.95rem; }
      .de-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem; align-items: start; }
      .de-item { margin: 0; padding: 0.75rem; border-radius: 0.5rem; border: 1px solid var(--color-separator); background: var(--color-bg); }
      .de-img { width: 100%; height: auto; display: block; }
      .de-cap { margin-top: 0.5rem; font-size: 0.875rem; color: var(--color-fg-secondary); }
    </style>
    <div class="de-wrap">
      <p class="de-desc">Expandable row trigger with leading icon container and chevron.</p>
<h4 class="de-variant">regular-expanded</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/expander/variants/regular-expanded/default.svg" alt="regular-expanded / default" loading="lazy" />
  <figcaption class="de-cap">regular-expanded / default</figcaption>
</figure>
</div>
<h4 class="de-variant">regular-collapsed</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/expander/variants/regular-collapsed/default.svg" alt="regular-collapsed / default" loading="lazy" />
  <figcaption class="de-cap">regular-collapsed / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/expander/variants/regular-collapsed/hover.svg" alt="regular-collapsed / hover" loading="lazy" />
  <figcaption class="de-cap">regular-collapsed / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/expander/variants/regular-collapsed/pressed.svg" alt="regular-collapsed / pressed" loading="lazy" />
  <figcaption class="de-cap">regular-collapsed / pressed</figcaption>
</figure>
</div>
<h4 class="de-variant">regular</h4>
<div class="de-grid">
<figure class="de-item">
  <img class="de-img" src="/designs/components/expander/variants/regular/default.svg" alt="regular / default" loading="lazy" />
  <figcaption class="de-cap">regular / default</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/expander/variants/regular/hover.svg" alt="regular / hover" loading="lazy" />
  <figcaption class="de-cap">regular / hover</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img" src="/designs/components/expander/variants/regular/pressed.svg" alt="regular / pressed" loading="lazy" />
  <figcaption class="de-cap">regular / pressed</figcaption>
</figure>
</div>
    </div>
  `,
};
