// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: apps/web/scripts/generate-storybook-design-exports.mjs
// Source: designs/screens/trade-flow-step-1/trade-flow-step-1.json

export default {
  id: "pages-trade-flow-step-1-design-export",
  title: "Reference/Pages/Trade Flow Step 1",
  tags: ['!autodocs'],
  parameters: {
    layout: "fullscreen",
    docs: { disable: true },
  },
};

export const DesignExport = {
  name: 'Design export',
  render: () => `
    <style>
      .de-wrap { padding: 1rem; }
      .de-desc { margin: 0 0 1rem; color: var(--color-fg-secondary); font-size: 0.875rem; }
      .de-variant { margin: 1rem 0 0.5rem; font-size: 0.95rem; }
      .de-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1rem; align-items: start; }
      .de-item { margin: 0; padding: 0.75rem; border-radius: 0.5rem; border: 1px solid var(--color-separator); background: var(--color-bg); }
      .de-img { width: 100%; height: auto; display: block; }
      .de-cap { margin-top: 0.5rem; font-size: 0.875rem; color: var(--color-fg-secondary); }
      .de-grid--screen { grid-template-columns: repeat(auto-fit, minmax(min(100%, 390px), 1fr)); }
      .de-img--screen { max-height: 85vh; object-fit: contain; object-position: top center; }
    </style>
    <div class="de-wrap">
      <p class="de-desc">Trade flow step 1 — order entry modal (account, quantity, amount) opened from position Buy/Sell.</p>
<h4 class="de-variant">desktop-default</h4>
<div class="de-grid de-grid--screen">
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/v" alt="desktop-default / 0" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 0</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/a" alt="desktop-default / 1" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 1</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/r" alt="desktop-default / 2" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 2</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/i" alt="desktop-default / 3" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 3</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/a" alt="desktop-default / 4" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 4</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/n" alt="desktop-default / 5" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 5</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/t" alt="desktop-default / 6" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 6</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/s" alt="desktop-default / 7" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 7</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1//" alt="desktop-default / 8" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 8</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/d" alt="desktop-default / 9" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 9</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/e" alt="desktop-default / 10" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 10</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/s" alt="desktop-default / 11" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 11</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/k" alt="desktop-default / 12" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 12</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/t" alt="desktop-default / 13" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 13</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/o" alt="desktop-default / 14" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 14</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/p" alt="desktop-default / 15" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 15</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/-" alt="desktop-default / 16" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 16</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/d" alt="desktop-default / 17" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 17</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/e" alt="desktop-default / 18" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 18</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/f" alt="desktop-default / 19" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 19</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/a" alt="desktop-default / 20" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 20</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/u" alt="desktop-default / 21" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 21</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/l" alt="desktop-default / 22" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 22</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/t" alt="desktop-default / 23" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 23</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1//" alt="desktop-default / 24" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 24</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/d" alt="desktop-default / 25" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 25</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/e" alt="desktop-default / 26" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 26</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/f" alt="desktop-default / 27" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 27</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/a" alt="desktop-default / 28" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 28</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/u" alt="desktop-default / 29" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 29</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/l" alt="desktop-default / 30" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 30</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/t" alt="desktop-default / 31" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 31</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/." alt="desktop-default / 32" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 32</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/s" alt="desktop-default / 33" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 33</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/v" alt="desktop-default / 34" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 34</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/g" alt="desktop-default / 35" loading="lazy" />
  <figcaption class="de-cap">desktop-default / 35</figcaption>
</figure>
</div>
<h4 class="de-variant">mobile-default</h4>
<div class="de-grid de-grid--screen">
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/v" alt="mobile-default / 0" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 0</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/a" alt="mobile-default / 1" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 1</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/r" alt="mobile-default / 2" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 2</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/i" alt="mobile-default / 3" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 3</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/a" alt="mobile-default / 4" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 4</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/n" alt="mobile-default / 5" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 5</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/t" alt="mobile-default / 6" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 6</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/s" alt="mobile-default / 7" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 7</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1//" alt="mobile-default / 8" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 8</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/m" alt="mobile-default / 9" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 9</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/o" alt="mobile-default / 10" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 10</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/b" alt="mobile-default / 11" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 11</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/i" alt="mobile-default / 12" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 12</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/l" alt="mobile-default / 13" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 13</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/e" alt="mobile-default / 14" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 14</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/-" alt="mobile-default / 15" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 15</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/d" alt="mobile-default / 16" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 16</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/e" alt="mobile-default / 17" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 17</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/f" alt="mobile-default / 18" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 18</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/a" alt="mobile-default / 19" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 19</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/u" alt="mobile-default / 20" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 20</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/l" alt="mobile-default / 21" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 21</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/t" alt="mobile-default / 22" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 22</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1//" alt="mobile-default / 23" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 23</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/d" alt="mobile-default / 24" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 24</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/e" alt="mobile-default / 25" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 25</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/f" alt="mobile-default / 26" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 26</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/a" alt="mobile-default / 27" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 27</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/u" alt="mobile-default / 28" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 28</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/l" alt="mobile-default / 29" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 29</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/t" alt="mobile-default / 30" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 30</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/." alt="mobile-default / 31" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 31</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/s" alt="mobile-default / 32" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 32</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/v" alt="mobile-default / 33" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 33</figcaption>
</figure>
<figure class="de-item">
  <img class="de-img de-img--screen" src="/designs/screens/trade-flow-step-1/g" alt="mobile-default / 34" loading="lazy" />
  <figcaption class="de-cap">mobile-default / 34</figcaption>
</figure>
</div>
    </div>
  `,
};
